
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
    }
    double n1=0,n2=0;
    String operator=null;
         boolean shif,degrad;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        bp = new javax.swing.JButton();
        bq = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        dd = new javax.swing.JTextField();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        dee = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        beq = new javax.swing.JButton();
        sh = new javax.swing.JButton();
        dis = new javax.swing.JTextField();
        bm = new javax.swing.JButton();
        bp1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        b16.setBackground(new java.awt.Color(153, 0, 153));
        b16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b16.setForeground(new java.awt.Color(255, 255, 204));
        b16.setText("1");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(204, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Shonar Bangla", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CALCULATOR");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 153, 153));

        b1.setBackground(new java.awt.Color(153, 0, 153));
        b1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 204));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(153, 0, 153));
        b2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 0));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(153, 0, 153));
        b3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 0));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(153, 0, 153));
        b4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 0));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(153, 0, 153));
        b7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 0));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(153, 0, 153));
        b5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 0));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(153, 0, 153));
        b6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 0));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(153, 0, 153));
        b8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 0));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(153, 0, 153));
        b9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 0));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(153, 0, 153));
        b0.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 0));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bd.setBackground(new java.awt.Color(153, 0, 153));
        bd.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bd.setForeground(new java.awt.Color(255, 255, 0));
        bd.setText(".");
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });

        bp.setBackground(new java.awt.Color(255, 0, 102));
        bp.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bp.setForeground(new java.awt.Color(255, 255, 0));
        bp.setText("+");
        bp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpActionPerformed(evt);
            }
        });

        bq.setBackground(new java.awt.Color(255, 0, 102));
        bq.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bq.setForeground(new java.awt.Color(255, 255, 0));
        bq.setText("/");
        bq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bqActionPerformed(evt);
            }
        });

        bdiv.setBackground(new java.awt.Color(255, 0, 102));
        bdiv.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bdiv.setForeground(new java.awt.Color(255, 255, 0));
        bdiv.setText("%");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });

        bmul.setBackground(new java.awt.Color(255, 0, 102));
        bmul.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bmul.setForeground(new java.awt.Color(255, 255, 0));
        bmul.setText("*");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        bc.setBackground(new java.awt.Color(255, 153, 153));
        bc.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bc.setForeground(new java.awt.Color(51, 0, 102));
        bc.setText("C");
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b11.setBackground(new java.awt.Color(0, 153, 153));
        b11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b11.setForeground(new java.awt.Color(255, 255, 204));
        b11.setText("Bin");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b13.setBackground(new java.awt.Color(0, 153, 153));
        b13.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b13.setForeground(new java.awt.Color(255, 255, 204));
        b13.setText("oct");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setBackground(new java.awt.Color(0, 153, 153));
        b14.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b14.setForeground(new java.awt.Color(255, 255, 204));
        b14.setText("X^.5");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setBackground(new java.awt.Color(0, 153, 153));
        b15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b15.setForeground(new java.awt.Color(255, 255, 204));
        b15.setText("Snh");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b17.setBackground(new java.awt.Color(0, 153, 153));
        b17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b17.setForeground(new java.awt.Color(255, 255, 204));
        b17.setText("pi");
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b18.setBackground(new java.awt.Color(0, 153, 153));
        b18.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b18.setForeground(new java.awt.Color(255, 255, 204));
        b18.setText("csh");
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b19.setBackground(new java.awt.Color(0, 153, 153));
        b19.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b19.setForeground(new java.awt.Color(255, 255, 204));
        b19.setText("log");
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b20.setBackground(new java.awt.Color(0, 153, 153));
        b20.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b20.setForeground(new java.awt.Color(255, 255, 204));
        b20.setText("X^3");
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b21.setBackground(new java.awt.Color(0, 153, 153));
        b21.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b21.setForeground(new java.awt.Color(255, 255, 204));
        b21.setText("lnx");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b22.setBackground(new java.awt.Color(0, 153, 153));
        b22.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b22.setForeground(new java.awt.Color(255, 255, 204));
        b22.setText("sn");
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        b23.setBackground(new java.awt.Color(0, 153, 153));
        b23.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b23.setForeground(new java.awt.Color(255, 255, 204));
        b23.setText("tnh");
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        b24.setBackground(new java.awt.Color(0, 153, 153));
        b24.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b24.setForeground(new java.awt.Color(255, 255, 204));
        b24.setText("X^Y");
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });

        b25.setBackground(new java.awt.Color(0, 153, 153));
        b25.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b25.setForeground(new java.awt.Color(255, 255, 204));
        b25.setText("e^X");
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });

        b26.setBackground(new java.awt.Color(0, 153, 153));
        b26.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b26.setForeground(new java.awt.Color(255, 255, 204));
        b26.setText("Hex");
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });

        b27.setBackground(new java.awt.Color(0, 153, 153));
        b27.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b27.setForeground(new java.awt.Color(255, 255, 204));
        b27.setText("n!");
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });

        b29.setBackground(new java.awt.Color(0, 153, 153));
        b29.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b29.setForeground(new java.awt.Color(255, 255, 204));
        b29.setText("cs");
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });

        b30.setBackground(new java.awt.Color(0, 153, 153));
        b30.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b30.setForeground(new java.awt.Color(255, 255, 204));
        b30.setText("tn");
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        b31.setBackground(new java.awt.Color(0, 153, 153));
        b31.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        b31.setForeground(new java.awt.Color(255, 255, 204));
        b31.setText("X^2");
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        b32.setBackground(new java.awt.Color(0, 153, 153));
        b32.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b32.setForeground(new java.awt.Color(255, 255, 204));
        b32.setText("ON");
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        b33.setBackground(new java.awt.Color(0, 153, 153));
        b33.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b33.setForeground(new java.awt.Color(255, 255, 204));
        b33.setText("OFF");
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });

        dee.setBackground(new java.awt.Color(0, 153, 153));
        dee.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        dee.setForeground(new java.awt.Color(255, 255, 204));
        dee.setText("Deg");
        dee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deeActionPerformed(evt);
            }
        });

        b35.setBackground(new java.awt.Color(0, 153, 153));
        b35.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        b35.setForeground(new java.awt.Color(255, 255, 204));
        b35.setText("Rad");
        b35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b35ActionPerformed(evt);
            }
        });

        beq.setBackground(new java.awt.Color(255, 153, 153));
        beq.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        beq.setForeground(new java.awt.Color(102, 0, 102));
        beq.setText("=");
        beq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beqActionPerformed(evt);
            }
        });

        sh.setBackground(new java.awt.Color(255, 153, 153));
        sh.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        sh.setForeground(new java.awt.Color(102, 0, 102));
        sh.setText("SHIFT");
        sh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shActionPerformed(evt);
            }
        });

        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });

        bm.setBackground(new java.awt.Color(255, 0, 102));
        bm.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bm.setForeground(new java.awt.Color(255, 255, 0));
        bm.setText("-");
        bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmActionPerformed(evt);
            }
        });

        bp1.setBackground(new java.awt.Color(255, 0, 102));
        bp1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bp1.setForeground(new java.awt.Color(255, 255, 0));
        bp1.setText("Ex");
        bp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(b14, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(b17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(b0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                            .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                                .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)
                                            .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(b8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bd, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                            .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bmul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bdiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b33, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(beq, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b35, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b32)
                        .addComponent(b33)
                        .addComponent(dee)
                        .addComponent(b35))
                    .addComponent(beq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bc)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bp)
                    .addComponent(bm)
                    .addComponent(bp1))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
 String i1=dd.getText()+b1.getText();
 dd.setText(i1);


        // TODO add your handling code here:t.setText(t.getText()+"1");
    }//GEN-LAST:event_b1ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        //t.setText(t.getText()+"9");
        String i9=dd.getText()+b9.getText();
 dd.setText(i9);
    }//GEN-LAST:event_b9ActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
dis.setText(dis.getText()+".");        
// TODO add your handling code here:
    }//GEN-LAST:event_bdActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
//t.setText(t.getText()+"2");   
 String i2=dd.getText()+b2.getText();
 dd.setText(i2);// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
//t.setText(t.getText()+"3");   
 String i3=dd.getText()+b3.getText();
 dd.setText(i3);// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
//t.setText(t.getText()+"4");        // TODO add your handling code here:
 String i4=dd.getText()+b4.getText();
 dd.setText(i4);
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
//t.setText(t.getText()+"5");
 String i5=dd.getText()+b5.getText();
 dd.setText(i5);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
//t.setText(t.getText()+"6");        // TODO add your handling code here:
   String i6=dd.getText()+b6.getText();
 dd.setText(i6);      // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
//t.setText(t.getText()+"7");  
 String i7=dd.getText()+b7.getText();
 dd.setText(i7);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
//t.setText(t.getText()+"8");
 String i8=dd.getText()+b8.getText();
 dd.setText(i8);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
//t.setText(t.getText()+"0");        // TODO add your handling code here:
   String i0=dd.getText()+b0.getText();
 dd.setText(i0);      // TODO add your handling code here:
    }//GEN-LAST:event_b0ActionPerformed

    private void bqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bqActionPerformed
n1=Double.parseDouble(dd.getText());
dd.setText(" ");
operator="/";
dis.setText(String.valueOf(n1)+"/ ");


// TODO add your handling code here:
    }//GEN-LAST:event_bqActionPerformed

    private void bpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpActionPerformed
     
n1=Double.parseDouble(dd.getText());
dd.setText(" ");
operator="+"; 
dis.setText(String.valueOf(n1)+"+ ");
// TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_bpActionPerformed

    private void bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmActionPerformed
        // TODO add your handling code here:
        n1=Double.parseDouble(dd.getText());
dd.setText(" ");
operator="-";  
dis.setText(String.valueOf(n1)+"- ");



        // TODO add your handling code here:
    }//GEN-LAST:event_bmActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
n1=Double.parseDouble(dd.getText());
dd.setText(" ");
operator="*";  
dis.setText(String.valueOf(n1)+"* ");

// TODO add your handling code here:
    }//GEN-LAST:event_bmulActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
n1=Double.parseDouble(dd.getText());
dd.setText(" ");
operator="%";   dis.setText(String.valueOf(n1)+"%");

// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_bdivActionPerformed

    private void beqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beqActionPerformed
String res;
        n2=Double.parseDouble(dd.getText());      // n2=Double.parseDouble(dis.getText());
        
double ans=0;
if("+".equals(operator)){
    ans=n1+n2;
    res=String.format("%.2f", ans);
    dd.setText(String.valueOf(n1)+"+"+String.valueOf(n2));
    dis.setText(res);
}
if("-".equals(operator)){
    ans=n1-n2;
    res=String.format("%.2f", ans);
    dd.setText(String.valueOf(n1)+"-"+String.valueOf(n2));
    dis.setText(res);
    
}
if("*".equals(operator)){
    ans=n1*n2;
    res=String.format("%.2f", ans);
    dd.setText(String.valueOf(n1)+"*"+String.valueOf(n2));
    dis.setText(res);
}
if("/".equals(operator)){
    ans=n1/n2;
    res=String.format("%.2f", ans);
    dd.setText(String.valueOf(n1)+"/"+String.valueOf(n2));
    dis.setText(res);
}
if("%".equals(operator)){
    ans=n1%n2;
    res=String.format("%.2f", ans);
    dd.setText(String.valueOf(n1)+"%"+String.valueOf(n2));
    dis.setText(res);
}
else if("X^Y".equals(operator)){
    ans=1;
    for(int i=0;i<n2;i++){
        ans=n1*ans;
    }    
    dd.setText(String.valueOf(n1)+"^("+String.valueOf(n2)+")");
    
      res=String.format("%.2f", ans);
      dis.setText(res);
}



dis.setText(" "+ans);
operator=null;
// TODO add your handling code here:
    }//GEN-LAST:event_beqActionPerformed

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
dis.setText(" ");
dd.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_bcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String be=null;
if(dd.getText().length()>0){
    StringBuilder sb=new StringBuilder(dd.getText());
    sb.deleteCharAt(dd.getText().length()-1);
    be=sb.toString();
    dd.setText(be);
}
        
        
       /* String s=dis.getText();
String s1=dd.getText();
dis.setText(s.substring(0, s.length()-1));
dd.setText(s1.substring(0, s1.length()-1));
        // TODO add your handling code here:*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
int a=Integer.parseInt(dd.getText());
 dis.setText("Bin("+Integer.toString(a)+")");
dd.setText(Integer.toString(a,2));

        // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
int a=Integer.parseInt(String.valueOf(dd.getText()));
 dis.setText("Oct("+Integer.toString(a)+")");
dd.setText(Integer.toString(a,8));
        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
 double ope=Double.parseDouble(String.valueOf(dd.getText()));        // TODO add your handling code here:
       
        dis.setText("("+dd.getText()+")^0.5");
        ope=Math.sqrt(ope);
        
        dd.setText(String.valueOf(ope));



        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText())); 
dis.setText("Sinh("+String.valueOf(ope)+")");
 ope=Math.sinh(ope);
        dd.setText(String.valueOf(ope));


        // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
double a;
                                   
double ope=Double.parseDouble(String.valueOf(dd.getText())); 
ope=Math.PI;
a=Double.parseDouble(String.valueOf(dd.getText()))*ope;

        dd.setText(String.valueOf(ope));





        // TODO add your handling code here:
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText())); 
dis.setText("Cosh("+String.valueOf(ope)+")");
 ope=Math.cosh(ope);
        dd.setText(String.valueOf(ope));        // TODO add your handling code here:
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
 double ope=Double.parseDouble(String.valueOf(dd.getText()));        // TODO add your handling code here:
       
        dis.setText("log("+dd.getText()+")");
        ope=Math.log10(ope);
        
        dd.setText(String.valueOf(ope));


        // TODO add your handling code here:
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText()));        // TODO add your handling code here:
       
        dis.setText(String.valueOf(dd.getText())+"^3");
        ope=ope*ope*ope;dd.setText(String.valueOf(ope));  


        // TODO add your handling code here:
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
 double ope=Double.parseDouble(String.valueOf(dd.getText()));        // TODO add your handling code here:
       
        dis.setText("ln("+dd.getText()+")");
        ope=Math.log(ope);
        
        dd.setText(String.valueOf(ope));
        // TODO add your handling code here:
    }//GEN-LAST:event_b21ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText())); 

if(!shif){
    if(!degrad){
       dis.setText("sin("+String.valueOf(ope)+")");
       ope=ope*0.0174532;
    }ope=Math.sin(ope);
    
}else{
    dis.setText("sin^-1("+String.valueOf(ope)+")");
    ope=Math.sin(ope)/0.0174532;
}  dd.setText(String.valueOf(ope));        // TODO add your handling code here:
  
        // TODO add your handling code here:
    }//GEN-LAST:event_b22ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText())); 
dis.setText("tanh("+String.valueOf(ope)+")");
 ope=Math.tanh(ope);
        dd.setText(String.valueOf(ope));        // TODO add your handling code here:
    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
n1=Double.parseDouble(dd.getText());
dd.setText(" ");
operator="X^Y"; 
dis.setText(String.valueOf(n1)+"^( ");        // TODO add your handling code here:
    }//GEN-LAST:event_b24ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
double ope=Math.exp(Double.parseDouble(String.valueOf(dd.getText())));
dis.setText("e^("+String.valueOf(ope)+")");
//dis.setText("tanh("+String.valueOf(ope)+")");
dd.setText(" ");

dis.setText(dd.getText()+ope);        // TODO add your handling code here:
    }//GEN-LAST:event_b25ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
int a=Integer.parseInt(dd.getText());
 dis.setText("Hex("+Integer.toString(a)+")");
dd.setText(Integer.toString(a,16));
        // TODO add your handling code here:
    }//GEN-LAST:event_b26ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText()));   
double fact=1;
dis.setText(dd.getText()+"!");
while(ope!=0){
    fact=fact*ope;
    ope--;
    
}
dd.setText(" ");
dd.setText(dd.getText()+fact);

// TODO add your handling code here:
    }//GEN-LAST:event_b27ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText())); 

if(!shif){
    if(!degrad){
       dis.setText("cos("+String.valueOf(ope)+")");
       ope=ope*0.0174532;
    }ope=Math.cos(ope);
    
}else{
    dis.setText("cos^-1("+String.valueOf(ope)+")");
    ope=Math.cos(ope)/0.0174532;
}  dd.setText(String.valueOf(ope));        // TODO add your handling code here:
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_b29ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText())); 

if(!shif){
    if(!degrad){
       dis.setText("tan("+String.valueOf(ope)+")");
       ope=ope*0.0174532;
    }ope=Math.tan(ope);
    
}else{
    dis.setText("tan^-1("+String.valueOf(ope)+")");
    ope=Math.tan(ope)/0.0174532;
}  dd.setText(String.valueOf(ope));        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_b30ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
double ope=Double.parseDouble(String.valueOf(dd.getText()));        // TODO add your handling code here:
       
        dis.setText(String.valueOf(dd.getText())+"^2");
        ope=ope*ope;dd.setText(String.valueOf(ope));  
         // TODO add your handling code here:
    }//GEN-LAST:event_b31ActionPerformed

    private void shActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shActionPerformed
if(!shif){
    shif=true;
}else{
    shif=false;
}



        // TODO add your handling code here:
    }//GEN-LAST:event_shActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        // TODO add your handling code here:
       b0.setEnabled(true);
     b1.setEnabled(true);
     b11.setEnabled(true);
     b13.setEnabled(true);
     b14.setEnabled(true);
     b15.setEnabled(true);
     b16.setEnabled(true);
     b17.setEnabled(true);
     b18.setEnabled(true);
     b19.setEnabled(true);
     b2.setEnabled(true);
     b20.setEnabled(true);
     b21.setEnabled(true);
     b22.setEnabled(true);
     b23.setEnabled(true);
     b24.setEnabled(true);
     b25.setEnabled(true);
     b26.setEnabled(true);
     b27.setEnabled(true);
     b29.setEnabled(true);
     b3.setEnabled(true);
     b30.setEnabled(true);
     b31.setEnabled(true);
   
     b35.setEnabled(true);
     b4.setEnabled(true);
     b5.setEnabled(true);
     b6.setEnabled(true);
     b7.setEnabled(true);
    b8.setEnabled(true);
     b9.setEnabled(true);
     bc.setEnabled(true);
    bd.setEnabled(true);
     bdiv.setEnabled(true);
  beq.setEnabled(true);
  bm.setEnabled(true);
  bmul.setEnabled(true);
 bp.setEnabled(true);
  bp1.setEnabled(true);
  bq.setEnabled(true);
  dd.setEnabled(true);
  dee.setEnabled(true);
 dis.setEnabled(true);
 jButton1.setEnabled(true);
 jLabel1.setEnabled(true);
  jPanel1.setEnabled(true);
  jPanel2.setEnabled(true);
 sh.setEnabled(true);
   
        
        
        
    }//GEN-LAST:event_b32ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        // TODO add your handling code here:
              b0.setEnabled(false);
     b1.setEnabled(false);
     b11.setEnabled(false);
     b13.setEnabled(false);
     b14.setEnabled(false);
     b15.setEnabled(false);
     b16.setEnabled(false);
     b17.setEnabled(false);
     b18.setEnabled(false);
     b19.setEnabled(false);
     b2.setEnabled(false);
     b20.setEnabled(false);
     b21.setEnabled(false);
     b22.setEnabled(false);
     b23.setEnabled(false);
     b24.setEnabled(false);
     b25.setEnabled(false);
     b26.setEnabled(false);
     b27.setEnabled(false);
     b29.setEnabled(false);
     b3.setEnabled(false);
     b30.setEnabled(false);
     b31.setEnabled(false);
     b35.setEnabled(false);
     b4.setEnabled(false);
     b5.setEnabled(false);
     b6.setEnabled(false);
     b7.setEnabled(false);
    b8.setEnabled(false);
     b9.setEnabled(false);
     bc.setEnabled(false);
    bd.setEnabled(false);
     bdiv.setEnabled(false);
  beq.setEnabled(false);
  bm.setEnabled(false);
  bmul.setEnabled(false);
 bp.setEnabled(false);
  bp1.setEnabled(false);
  bq.setEnabled(false);
  dd.setEnabled(false);
  dee.setEnabled(false);
 dis.setEnabled(false);
 jButton1.setEnabled(false);
 jLabel1.setEnabled(false);
  jPanel1.setEnabled(false);
  jPanel2.setEnabled(false);
 sh.setEnabled(false);
   
 
    }//GEN-LAST:event_b33ActionPerformed

    private void deeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deeActionPerformed
        // TODO add your handling code here:
        boolean degrad = false;
    }//GEN-LAST:event_deeActionPerformed

    private void b35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b35ActionPerformed
        // TODO add your handling code here:
        boolean degrad = true;
    }//GEN-LAST:event_b35ActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddActionPerformed

    private void bp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bp1ActionPerformed
 double ope=Double.parseDouble(dd.getText());        // TODO add your handling code here:
        double exp=10;
        double p;
        dis.setText("10^("+dd.getText()+")");
        p=Math.pow(exp, ope);
        dd.setText(" ");
        dd.setText(dd.getText()+p);
    }//GEN-LAST:event_bp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b11;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b35;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bc;
    private javax.swing.JButton bd;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton beq;
    private javax.swing.JButton bm;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bp;
    private javax.swing.JButton bp1;
    private javax.swing.JButton bq;
    private javax.swing.JTextField dd;
    private javax.swing.JButton dee;
    private javax.swing.JTextField dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sh;
    // End of variables declaration//GEN-END:variables
}